### ISSUE TITLE
RPTCL command

### ISSUE THREAD

**Issue by oe1kbc** [g4klx/DMRGateway#28]
After stopping MMDVMHost by hand with str+c all three connected masters stay logged in on DMRGHateway

Only "MMDVM Network, The connected MMDVM is closing down" is done.

Stop DRMGateway by hand with strg+c - DMRGateway is closing DMR Networks XLX-1, DMR-1 and DMR-2 and stop connections.

73 de Kurt
OE1KBC

**Comment by g0wfv** [comment]
Yes, this was intentional on my part when I put the RPTCL modifications into the code.  It's telling you the connected MMDVM is closing intentionally (through manual interaction as opposed to a crash!)  DMRGateway will retain your connections to the connected masters unless you close it down manually too.
