### ISSUE TITLE
Question: How to disable send aprs data to APRS.fi?

### ISSUE THREAD

**Issue by sp2ong** [g4klx/DMRGateway#82]
Hi,

How to disable send aprs data to APRS.fi by DMRgateway?

**Comment by g4klx** [comment]
The DMR Gateway doesn't send APRS data to APRS.fi, that is done by the different masters. DMR Gateway and MMDVM Host don't understand GPS data on DMR because there is no standard. If you mean sending only the location of the MMDVM itself, that is also done by the masters. That could be controlled by the DMR Gateway, but currently isn't. If you want to control it, then it'd be a nice project for someone.

**Comment by sp2ong** [comment]
Thank you for your explanations.
